server:
  servlet:
    context-path: /api

application:
  db-path: heroes.db

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: heroes_id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3309/db
    username: gorr
    password: pswd123
    driver-class-name: com.mysql.jdbc.Driver
